config/routes.rb
Fedexday::Application.routes.draw do
  resources :ideas do
    member do
      put 'scratch'
    end
  end
  
  resources :endorsements
  resources :comments

  root :to => 'ideas#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  
  validates :body, :presence => true
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :idea
  
  validates :name, :presence => true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :endorsements, :dependent => :destroy
  
  validates :title, :presence => true
  validates :body, :presence => true
  
  scope :long_expired, where("(updated_at < '#{1.week.ago}' AND scratched = 't') OR (updated_at < '#{9.months.ago}')")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.create(params[:comment])
    @comment.idea.update_attribute(:updated_at, Time.now)

    redirect_to @comment.idea
  end
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  # POST /endorsements
  # POST /endorsements.json
  def create
    @endorsement = Endorsement.create(params[:endorsement])
    @endorsement.idea.update_attribute(:updated_at, Time.now)
    
    redirect_to @endorsement.idea
  end

  # DELETE /endorsements/1
  # DELETE /endorsements/1.json
  def destroy
    @endorsement = Endorsement.find(params[:id])
    idea = @endorsement.idea
    @endorsement.destroy

    redirect_to idea
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.order("scratched asc, updated_at desc")

    Idea.long_expired.each do |i|
      i.destroy
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])
    @new_comment = Comment.new(:idea_id => @idea.id)
    @new_endorsement = Endorsement.new(:idea_id => @idea.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, :notice => 'Idea was successfully created.' }
        format.json { render :json => @idea, :status => :created, :location => @idea }
      else
        format.html { render :action => "new" }
        format.json { render :json => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, :notice => 'Idea was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /ideas/1/scratch
  # Allows to "scratch/unscratch" an idea, which doesn't destroy it, but will mark/unmark an idea as "scratched out"
  def scratch
    @idea = Idea.find(params[:id])
    
    @idea.update_attribute(:scratched, !@idea.scratched)
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/ideas/_comment_form.haml
%b="New comment"
=form_for @new_comment do |f|
  =f.hidden_field :idea_id
  =f.text_area :body, :size => "50x10"
  %br
  =f.submit "Add comment"

app/views/ideas/_comments_list.haml
%br
%br
%h2="Comments"
-@idea.comments.each do |c|
  .comment-time
    %b=time_ago_in_words(c.updated_at) + " ago"
  .comment-text
    =simple_format(c.body)
    %br
    %br
=render 'comment_form'

app/views/ideas/_endorsement_form.haml
Enter your name to endorse this idea
=form_for @new_endorsement do |f|
  =f.hidden_field :idea_id
  =f.text_field :name
  =f.submit "Endorse"

app/views/ideas/_endorsements_list.haml
%h3="Currently endorsed by"
-@idea.endorsements.each do |e|
  %span=link_to "x", e, :method => :delete
  =e.name
  %br
%br
=render 'endorsement_form'

app/views/ideas/_form.haml
Write a brief outline of your idea.
=form_for(@idea) do |f|
  -if @idea.errors.any?
    #error_explanation
      %h2=pluralize(@idea.errors.count, "error") + " prohibited this idea from being saved:"

      %ul
        -@idea.errors.full_messages.each do |msg|
          %li= msg
  %br
  =f.label :title
  %br
  =f.text_field :title
  %br
  %br
  =f.label :summary
  %br
  =f.text_area :body
  .actions
    =f.submit
    =link_to 'Cancel', @idea

app/views/ideas/_idea_layout.haml
%span{:class=>'idea-title'}
  =@idea.title
=link_to 'edit', edit_idea_path(@idea)
%p{:class=>'idea-text'}=simple_format @idea.body

app/views/ideas/edit.haml
%h1="Edit idea"
=render 'form'

app/views/ideas/index.haml
%b=link_to 'Submit new idea', new_idea_path
%br
%br
.compact-table
  %table
    %tr
      %th{:class=>'column-integer'}
      %th{:class=>'column-integer'}="▲"
      %th{:class=>'column-string'}="Ideas"
      %th{:class=>'column-integer'}="Comments"
      %th{:class=>'column-string', :width=>"15%"}="Last activity"
    - @ideas.each do |idea|
      %tr
        %td=link_to "X", scratch_idea_path(idea), :method => :put
        %td{:style=>"text-align: center"}
          %b
            =idea.endorsements.count
        %td{:style=>"text-align: left"}
          - if idea.scratched
            %strike=link_to idea.title, idea
          -else
            =link_to idea.title, idea
        %td{:style=>"text-align: center"}
          %b
            =idea.comments.count
        %td{:style=>"text-align: left"}=time_ago_in_words(idea.updated_at) + " ago"

app/views/ideas/new.html.haml
%h1="New idea"
=render 'form'

app/views/ideas/show.haml
%p{:id=>"notice"}=notice

#idea
  =render 'idea_layout'
#comments
  =render 'comments_list'
#endorsements
  =render 'endorsements_list'

app/views/layouts/application.haml
<!DOCTYPE html>
%html
  %head
    %title="Fedexday"
    <link href='http://fonts.googleapis.com/css?family=Esteban|Ruluko|Montserrat' rel='stylesheet' type='text/css'>
    =stylesheet_link_tag "application"
    =javascript_include_tag "application"
    =csrf_meta_tags
  %body
    .min-width-920
      .content-wrapper
        =render 'partials/header'
        .page-content-wrapper
          =yield

app/views/partials/_header.haml
#title-image
  =link_to (image_tag 'title-logo.png'), :root
#title-text
  %span{:id=>'title-head'}=link_to "FedEx Day idea box", :root
  %br
  %span{:id=>'title-subhead'}=link_to "Submit an idea. Get feedback.", :root
  %br
#title-countdown
  %b="FedEx day"
  March 15, 2012
%br